name: comitNames

on:
  push:
    branches:
      - main

jobs:
  update-commit-messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Change Commit Names
      run: |
        git config user.name "GitHub Action Bot"
        git config user.email "action@github.com"
        
        commit_count=$(git rev-list --count HEAD)
        if [ "$commit_count" -gt 1 ]; then
          git rebase -i HEAD~"$commit_count" << EOF
          exec git commit --amend -m "Sophia V-1"
          EOF
        else
          echo "Not enough commits to rebase."
        fi

        git push --force
